spring.application.name=expense-manager-mt
server.port=${PORT:8080}
spring.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres?sslmode=require}
spring.datasource.username=${SUPABASE_DB_USERNAME:postgres.unbuqptxmnmgrqvldlea}
spring.datasource.password=${SUPABASE_DB_PASSWORD:supadbbase1234}
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=10000
spring.datasource.hikari.validation-timeout=5000
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.serialization.write-dates-as-timestamps=false
